### ISSUE TITLE
Program Language

### ISSUE THREAD

**Issue by abandoh** [noisycat05/Backroom-net#4]
#Language
Pure Basic is relatively a new language. It would have been helpful to use an other language.

# Issues
 
Bugs happen in code. I understand this and any feedback is great!
However, Here are some things to think about when making an issue statement.

* Operating system
  Please include Your operating system in the issue statement so I can test and see if the Operating system is the problem.
  It shouldn't be, but the native OS For Backroom Is Win10(x64). If your Using Linux, I'm sorry but good luck. 

* Any Error Log?
  If so, Include it in the Issue report.

* Does an error Message Mention any Database or Data file?
  Check to see if the permissions in that folder didn't change and then Look to the line below.
  If Not, Send Any, Database or Program Written File to me that seems to Cause a problem.

* Is this problem Reproduceable?
  If so, Tell me step by step how it happened!

Thats about it! If there is any other information about the Issue, Just mention it and we will see what we can do about it!

**Comment by noisycat05** [comment]
@abandoh , Purebasic has been around since 09/09/2000 and is very well built. It has a good and Efficient Compiler, Well structured and diverse library of commands and is very versatile. I selected this language for a reason and please Read The Issue Guide next time you post an issue however It will be taken into concentration. There will be many Updates to the code before the first official Release, Things will change Till then.

**Comment by noisycat05** [comment]
This Issue was closed and will be Used for future improvements. 

# Issue was closed Because of Failure to Conform to Issue Template
